### PR TITLE
Feature/analysis to result

### LINKED ISSUE #29: Show documents in pivot table cell
It should be possible to click on any cell in the pivot table in the analysis and show the found documents. This can be done by creating a query for this specific set and executing this one. It might be sensible to add this to the breadcrumb to be able to go back to the overall results.

### PR DESCRIPTION
**Pull request by oktaal**
This finally resolves #29 It adds the functionality to click on a cell in the pivot table of the analysis table, the user will then be redirect back to results with the filters selected to show the documents contained in that cell. This also adds xpath-filters which can currently only be added by the analysis component (e.g. the `@lemma`-attribute of `$node4` should be `"mango"`). I've also added a small bonus feature to copy the selected filters into the xpath query, this button should be visible when any filter is active (regardless of whether the user selected the filter themself or it has been added by the `AnalysisComponent`). I also enabled TSLint on my machine and removed a whole bunch of red squiggly lines whenever I edited a file.

### CODE REVIEW

**Comment by oktaal** [comment]
No, those numbers should match. Unless the number exceeds the result limit, then it will be capped at that (e.g. 500). Could you give an example?

**Comment by JeltevanBoheemen** [comment]
Tried with //node as Xpath query, sarahtest corpus. Clicked both squares highlighted in screenshot below. In both cases, returned all results (32, see screenshot)

untitled-2
screen shot 2018-10-22 at 17 07 23

**Comment by oktaal** [comment]
Oops! The root node need to be filtered somewhat differently. Last commit should fix this hopefully.

**Comment by JeltevanBoheemen** [comment]
Yep that work!

**Pull request merged**
